<a href="https://colab.research.google.com/github/hyj378/011/blob/ML_basic_inyt/9%EA%B0%95_XOR%EA%B5%AC%ED%98%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#XOR

In [0]:
#선형 예측 Linear Regression ->hypothesis함수로 1차방정식 이용
#분리 Logistic classification ->hypothesis함수로 sigmoid이용 (2종류 구분)
#분리 Logistic classification ->hypothesis함수로 sofrmax이용 (다종류 구분)
import tensorflow as tf
import numpy as np
x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
W = tf.Variable(tf.random_normal([2, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  
  for step in range(10001):
    sess.run(train, feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0:
      print(step, sess.run(cost, feed_dict={X: x_data, Y:y_data}), sess.run(W))
  h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X: x_data, Y:y_data})
  print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)

0 0.78359926 [[0.53903866]
 [1.58815   ]]
1000 0.69318056 [[0.02130462]
 [0.02333232]]
2000 0.6931472 [[0.00043613]
 [0.00043997]]
3000 0.6931472 [[8.5803276e-06]
 [8.5869715e-06]]
4000 0.6931472 [[1.596745e-07]
 [1.588678e-07]]
5000 0.6931472 [[1.3285231e-07]
 [1.3204561e-07]]
6000 0.6931472 [[1.3285231e-07]
 [1.3204561e-07]]
7000 0.6931472 [[1.3285231e-07]
 [1.3204561e-07]]
8000 0.6931472 [[1.3285231e-07]
 [1.3204561e-07]]
9000 0.6931472 [[1.3285231e-07]
 [1.3204561e-07]]
10000 0.6931472 [[1.3285231e-07]
 [1.3204561e-07]]

Hypothesis:  [[0.5]
 [0.5]
 [0.5]
 [0.5]] 
Correct:  [[0.]
 [0.]
 [0.]
 [0.]] 
Accuracy:  0.5


하나의 함수모델로 XOR을 분류하기 어렵다!

#AND / OR

######밑바닥부터 시작하는 딥러닝 참조

######가중치를 직접 주어 함수만들기

In [0]:
def NOT(x1):
    if x1 <= 0:
    return 1
  else:
    return 0
  
def AND(x1, x2):
  x = np.array([x1, x2])
  w = np.array([0.5, 0.5])
  b = -0.7
  tmp = np.sum(w*x) + b
  if tmp <= 0:
    return 0
  else:
    return 1
  
def OR(x1 ,x2):
  x = np.array([x1, x2])
  w = np.array([0.5, 0.5])
  b = -0.2
  tmp = np.sum(x*w) + b
  if tmp <= 0:
    return 0
  else:
    return 1
  
def XOR(x1, x2):
  s1 = AND(x1, x2)
  s1 = NOT(s1)  #이거를 하나로 묶어 s1 = NAND(x1, x2)
  s2 = OR(x1, x2)
  y = AND(s1, s2)
  return y

In [0]:
import tensorflow as tf
import numpy as np
x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(100001): #100001회로 늘렸다
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, sess.run(cost, feed_dict={
                  X: x_data, Y: y_data}), sess.run([W1, W2]))

    h, c, a = sess.run([hypothesis, predicted, accuracy],feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)


0 1.0545385 [array([[ 0.42808506,  0.09939292],
       [-0.1243186 ,  1.7933985 ]], dtype=float32), array([[ 0.07821158],
       [-1.6252916 ]], dtype=float32)]
1000 0.64218545 [array([[0.69036895, 1.7687551 ],
       [0.23204991, 1.9073644 ]], dtype=float32), array([[ 0.8547142],
       [-2.1259992]], dtype=float32)]
2000 0.4072173 [array([[2.3193765, 3.070557 ],
       [2.2161984, 3.0366983]], dtype=float32), array([[ 2.6975062],
       [-4.045318 ]], dtype=float32)]
3000 0.13060834 [array([[4.1887703, 3.9980526],
       [4.171562 , 3.9871013]], dtype=float32), array([[ 5.56862 ],
       [-6.172926]], dtype=float32)]
4000 0.06459529 [array([[4.949399 , 4.439242 ],
       [4.9409385, 4.434311 ]], dtype=float32), array([[ 7.0026193],
       [-7.4916425]], dtype=float32)]
5000 0.041272797 [array([[5.354852 , 4.6983385],
       [5.349102 , 4.6953173]], dtype=float32), array([[ 7.866957],
       [-8.34193 ]], dtype=float32)]
6000 0.029907392 [array([[5.6195   , 4.8765182],
       [5.61505

강의대로 했을때 계속 정확도가 0.5로 나왔는데 학습횟수를 늘리거나  공개된 코드처럼  random seed를777로 하면 1.0로 나온다

##Wide NN for XOR

In [0]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)

x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([10, 1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})

    h, c, a = sess.run([hypothesis, predicted, accuracy],feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)



Hypothesis:  [[0.00507385]
 [0.9945274 ]
 [0.9938022 ]
 [0.00704323]] 
Correct:  [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:  1.0


##Deep NN for XOR

In [0]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)

x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

W1 = tf.Variable(tf.random_normal([2, 10]), name='weight1')
b1 = tf.Variable(tf.random_normal([10]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([10, 10]), name='weight2')
b2 = tf.Variable(tf.random_normal([10]), name='bias2')
layer2 = tf.sigmoid(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([10, 10]), name='weight3')
b3 = tf.Variable(tf.random_normal([10]), name='bias3')
layer3 = tf.sigmoid(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([10, 1]), name='weight4')
b4 = tf.Variable(tf.random_normal([1]), name='bias4')
hypothesis = tf.sigmoid(tf.matmul(layer3, W4) + b4)

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) *
                       tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})

    h, c, a = sess.run([hypothesis, predicted, accuracy],feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect: ", c, "\nAccuracy: ", a)



Hypothesis:  [[5.8153545e-04]
 [9.9895930e-01]
 [9.9862421e-01]
 [1.4965999e-03]] 
Correct:  [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:  1.0


##exercise

In [0]:
import tensorflow as tf
import numpy as np
old_v = tf.logging.get_verbosity()
tf.logging.set_verbosity(tf.logging.ERROR)

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [0]:
nb_classes = 10
learning_rate = 0.1

X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, nb_classes]) #one_hot

W1 = tf.Variable(tf.random_normal([784, 100]), name = 'weight1')
b1 = tf.Variable(tf.random_normal([100]), name = 'bias1')
layer1 = tf.nn.softmax(tf.matmul(X, W1) + b1)

W2 = tf.Variable(tf.random_normal([100, 100]), name = 'weight2')
b2 = tf.Variable(tf.random_normal([100]), name = 'bias2')
layer2 = tf.nn.softmax(tf.matmul(layer1, W2) + b2)

W3 = tf.Variable(tf.random_normal([100, 50]), name = 'weight3')
b3 = tf.Variable(tf.random_normal([50]), name = 'bias3')
layer3 = tf.nn.softmax(tf.matmul(layer2, W3) + b3)

W4 = tf.Variable(tf.random_normal([50, nb_classes]), name = 'weight4')
b4 = tf.Variable(tf.random_normal([nb_classes]), name = 'bias4')
hypothesis = tf.nn.softmax(tf.matmul(layer3, W4) + b4)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
train = tf.train.GradientDescentOptimizer(learning_rate = learning_rate).minimize(cost)

is_correct = tf.equal(tf.arg_max(hypothesis, 1), tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [0]:
#arg_max의 원소 1은 차원에 대한 원소!
a = [#0차원 
    [ #1차원
        [ #2차원
            [1,2,3,4],
            [9,10,11,12] ,
            [5,6,7,8],
        ],
        [ #2차원
            [13,14,15,16],#3차원
            [17,18,19,20], 
            [21,22,25,24]
        ]
    ]
]
print(np.array(a).ndim)

with tf.Session() as sess:
  b = tf.arg_max(a, 0).eval()
  print(b, '\n')
  
  c = tf.arg_max(a, 1).eval()
  print(c, '\n')
  
  d = tf.arg_max(a, 2).eval()
  print(d, '\n')
  
  e = tf.arg_max(a, 3).eval()
  print(e, '\n')
  

4
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]] 

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 

[[[1 1 1 1]
  [2 2 2 2]]] 

[[[3 3 3]
  [3 3 2]]] 



In [0]:
training_epochs = 15
batch_size = 100

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for epoch in range(training_epochs):
    avg_cost=0
    total_batch = int(mnist.train.num_examples/batch_size)
    
    for step in range(total_batch):
      batch_xs, batch_ys = mnist.train.next_batch(batch_size)
      c, _ =sess.run([cost, train], feed_dict={X: batch_xs, Y: batch_ys})
      avg_cost += c/total_batch
      
    print('Epoch: ', '%04d'%(epoch+1), '회차 시도', 'cost =','{:.9f}.'.format(avg_cost)) 
  print('학습종료\n')
  
  print('Accuracy: ', accuracy.eval(session=sess, feed_dict={X : mnist.test.images, Y: mnist.test.labels}))

Epoch:  0001 회차 시도 cost = 2.361468370.
Epoch:  0002 회차 시도 cost = 2.299384060.
Epoch:  0003 회차 시도 cost = 2.296324273.
Epoch:  0004 회차 시도 cost = 2.292810603.
Epoch:  0005 회차 시도 cost = 2.287308013.
Epoch:  0006 회차 시도 cost = 2.277925830.
Epoch:  0007 회차 시도 cost = 2.261516134.
Epoch:  0008 회차 시도 cost = 2.231581639.
Epoch:  0009 회차 시도 cost = 2.175398827.
Epoch:  0010 회차 시도 cost = 2.074475345.
Epoch:  0011 회차 시도 cost = 1.948511219.
Epoch:  0012 회차 시도 cost = 1.801095715.
Epoch:  0013 회차 시도 cost = 1.691067862.
Epoch:  0014 회차 시도 cost = 1.623682512.
Epoch:  0015 회차 시도 cost = 1.584810056.
학습종료

Accuracy:  0.3205


deep과 wide를 적용했더니 정확도가 더 떨어진다 검색해봤더니 나만 발생하는 문제는 아닌것 같다 각 요소가 결과에 미치는 값(편미분값(?))이 각각 너무 작아서 그런걸까?

#Tensorboard

[참조링크 here](https://zzsza.github.io/data/2018/08/30/google-colab/#tensorboard-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)

[참조 here](https://www.dlology.com/blog/quick-guide-to-run-tensorboard-in-google-colab/)


In [0]:
sess.close()

In [0]:
LOG_DIR = 'drive/tb_logs' #LOG_DIR을 사용하면 구글내에 log폴더 생성

#ngrok:secure tunnels to localhost
#방화벽 넘어서 외부에서 로컬에 접솔 가능하게 하는 터널 프로그램
#setup ngrok and run TensorBoard on Colab
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip

import os
if not os.path.exists(LOG_DIR): #디렉토리 존재 유무를 확인하는 파이썬 
  os.makedirs(LOG_DIR)

#Get tensorboard in the background
LOG_DIR ='drive/tb_logs' #구글 내 드라이브에 data, tb_logs 폴더 생성
get_ipython().system_raw(
    'tensorboard --logdir {} --host 0.0.0.0 --port 6006 &'
    .format(LOG_DIR)
) 

#Launch ngrok background process
#http://localhost:4040/api/tunnels 자신의 컴퓨터 localhost에 텐서보드페이지가 생성
get_ipython().system_raw('./ngrok http 6006 &')
!curl -s http://localhost:4040/api/tunnels | python3 -c \
      "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

In [0]:
!pip install -U tensorboardcolab

Requirement already up-to-date: tensorboardcolab in /usr/local/lib/python3.6/dist-packages (0.0.22)


In [0]:
from tensorboardcolab import *
tbc=TensorBoardColab()

Google storage에서 파일읽기


```
!pip3 install gcsfs dask 

import gcsfs

from google.colab import auth
auth.authenticate_user()

fs = gcsfs.GCSFileSystem(project='project_name')
with fs.open('주소') as f:
    df = pd.read_csv(f)
```

gcsfs
Pythonic file-system for Google Cloud Storage
[here](https://gcsfs.readthedocs.io/en/latest/)

dask Dask is a flexible library for [parallel computing](https://ko.wikipedia.org/wiki/%EB%B3%91%EB%A0%AC_%EC%BB%B4%ED%93%A8%ED%8C%85)
 in Python. [here](https://docs.dask.org/en/latest/)
 
 [stackoverflow](https://stackoverflow.com/questions/47818822/can-i-use-tensorboard-with-google-colab)

In [0]:
!pip3 install gcsfs dask 

import gcsfs

from google.colab import auth
auth.authenticate_user()
fs = gcsfs.GCSFileSystem(project='project_name')

In [0]:
import tensorflow as tf
a = tf.constant(3.0)
b = tf.constant(5.0)
c = a*b

c_summary = tf.summary.scalar('point', c)
merged = tf.summary.merge_all()

with tf.Session() as sess:
  writer=tf.summary.FileWriter('./ngrok http 6006 &')
  
  result = sess.run([merged])
  
  sess.run(tf.global_variables_initializer())
  
  writer.add_summary(result[0])

InvalidArgumentError: ignored

In [0]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777)

#x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]], dtype=np.float32)
#y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

x_data = [[0, 0],
          [0, 1],
          [1, 0],
          [1, 1]]
y_data = [[0],
          [1],
          [1],
          [0]]

X = tf.placeholder(tf.float32, [None, 2], name='x')
Y = tf.placeholder(tf.float32, [None, 1], name='y')

#scope로 정리하기
with tf.name_scope("layer1") as scope:
  W1 = tf.Variable(tf.random_normal([2, 2]), name='weight1')
  b1 = tf.Variable(tf.random_normal([2]), name='bias1')
  layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)
  #step 1 logging
  w1_hist = tf.summary.histogram("weights1", W1)
  b1_hist = tf.summary.histogram("biases1", b1)
  layer1_hist = tf.summary.histogram("layer1", layer1)

with tf.name_scope("layer2") as scope:
  W2 = tf.Variable(tf.random_normal([2, 1]), name='weight2')
  b2 = tf.Variable(tf.random_normal([1]), name='bias2')
  hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)
  #step 1 logging
  w2_hist = tf.summary.histogram("weights2", W2)
  b2_hist = tf.summary.histogram("biases2", b2)
  hypothesis_hist = tf.summary.histogram("hypothesis", hypothesis)

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

#step 1 logging
cost_summ = tf.summary.scalar("cost", cost)

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))


with tf.Session() as sess:
  
  #step 2 summary
  summary = tf.summary.merge_all()
  sess.run(tf.global_variables_initializer())
  
  #Create summary writer
  writer = tf.summary.FileWriter("./ngrok http 6006 &")
  writer.add_graph(sess.graph)
  
  
  for step in range(10001):
    s, _ = sess.run([summary, train], feed_dict={X: x_data, Y: y_data})
    writer.add_summary(s, global_step = step)

InvalidArgumentError: ignored