<a href="https://colab.research.google.com/github/hyj378/011/blob/ML_basic_inyt/%EB%94%A5%EB%9F%AC%EB%8B%9D%EC%9D%98_%EA%B8%B0%EB%B3%B8_%EA%B0%9C%EB%85%90_8%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##딥러닝의 기본개념 8강 강의

####뉴런의 발견
-> 인공 뉴런도 만들 수 있지 않을까?

####AND, OR의 구현

####XOR구현의 실패
-> 불가능하구나

####neural network의 다양한 구현

paul Werbos와 hinton의 
Backpropagation방법을 이용한 neural network -> 
minsky교수의 'w과 b를 학습을 시킬 수 가 없다'를 해결

라쿤 교수의 고양이 실험 -> 생물체가 시각정보를 인식할때 한번에 정보 전체를(그림 전체를) 인식하는 것이 아니라 일부를 담당하는 신경망이 있고 그것이 나중에 조합되는것이 아닐까 -> Convolutional Neural Networks

####복잡한 문제를 풀면 너무 층이 두꺼워진다
복잡한 문제를 풀때 Backpropagation의 방법을 이용하면 error정보가 뒤로 돌아갈수록 약해져(데이터 손실) 학습이 어려워진다 또한 다른 형태의 알고리즘이 등장하고,  그 알고리즘들이 neural network알고리즘보다 높은 성능을 보이기 시작했다
->인공신경망알고리즘의 두번째 침체기

####불가능한것이 아니다 초기값을 잘 주면 돼!
->breakthrough등장! 
이름을 인공신경망적 알고리즘을 딥러닝 알고리즘이라고 바꿔서 다시 인기몰이를 한다

텐서를 다루는 방법?!
###ML lab 08: Tensor Manipulation

노드는 하나의 자료형이라고 할 수 있다.
나도 아직 개념을 확실히 잡지는 못했지만
텐서를 하나의 구조체 자료형으로 이해하자

텐서는 다른 operation(우리가 만든 노드, 함수)등을 흘러다닌다!

*****
tf.constant, 일반 배열, numpy배

In [31]:

import tensorflow as tf
import numpy as np
a = np.array([0, 1, 2])
b = [0,1,2,[0, 1, 2],[3, 4, 5]]
c = tf.constant([0,1,2])

print(a)
print(b)
print(c)

#sess = tf.Session
print(c.eval,'\n', c)
print(c[0])

[0 1 2]
[0, 1, 2, [0, 1, 2], [3, 4, 5]]
Tensor("Const_7:0", shape=(3,), dtype=int32)
<bound method Tensor.eval of <tf.Tensor 'Const_7:0' shape=(3,) dtype=int32>> 
 Tensor("Const_7:0", shape=(3,), dtype=int32)
Tensor("strided_slice_1:0", shape=(), dtype=int32)


In [79]:
import numpy as np
import pprint
#pp = pprint.PrettyPrinter()
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pprint.pprint(a)
pprint.pprint(b)
pprint.pprint(c) #더 이쁘게 출력하는 python함수라는데 사용법은 모르겠음

print('\n', t, '\n')
pprint.pprint(t)

array([0, 1, 2])
[0, 1, 2, [0, 1, 2], [3, 4, 5]]
<tf.Tensor 'Const_7:0' shape=(3,) dtype=int32>

 [0. 1. 2. 3. 4. 5. 6.] 

array([0., 1., 2., 3., 4., 5., 6.])


In [80]:
#array slicing with numpy
print(t.ndim)#차원
print(t.shape)#형태
print(t[0], t[1], t[2])
print(t[2:5], t[5:-1])
t_ = t[:, 0: -2]
print(t_)

1
(7,)
0.0 1.0 2.0
[2. 3. 4.] [5.]


IndexError: ignored

위의 오류는 t가 일차원 배열인데 슬라이싱을 마치 n차원(n>1)배열처럼 해버려서 생긴 오류입니다 아레처럼 바꾸면 해결됩니다

In [81]:
t = np.array([[0., 1., 2., 3., 4., 5., 6.], [0., 1., 2., 3., 4., 5., 6.],\
              [0., 1., 2., 3., 4., 5., 6.]])
t_ = t[0:-1, 0: -2]
print(t_)

t_ = t[0:, 0: -2]
print('\n', t_, '\n')

pprint.pprint(t)
print(t.ndim)
print(t.shape)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]] 

array([[0., 1., 2., 3., 4., 5., 6.],
       [0., 1., 2., 3., 4., 5., 6.],
       [0., 1., 2., 3., 4., 5., 6.]])
2
(3, 7)


##Shape, Rank, Axis


In [82]:
t = tf.constant([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],\
                [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
sess = tf.Session()

sess.run(t)
print(tf.shape(t))

sess.close()

Tensor("Shape_20:0", shape=(3,), dtype=int32)


In [83]:
t = tf.constant([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],\
                [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

tf.shape(t)

<tf.Tensor 'Shape_21:0' shape=(3,) dtype=int32>

In [98]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],\
                [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])

sess = tf.InteractiveSession()
tf.shape(t).eval()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


array([1, 2, 3, 4], dtype=int32)

위의 오류는 InteractiveSession을 반복실행해서 발생한 오류이고, eval()을 그냥 실행하면 강의처럼 실행되지 않는데 Session이 실행되는 동안 eval()이 가능한가봐요! 

[tf.InteractiveSession](https://www.tensorflow.org/api_docs/python/tf/InteractiveSession)

그런데 Seeion실행이 안되어도 tensor.eval은 실행되던데 왜 그럴까요?

[tf.Tensor](https://www.tensorflow.org/api_docs/python/tf/Tensor)

In [99]:
sess.close()
tf.shape(t).eval()

array([1, 2, 3, 4], dtype=int32)

In [100]:
sess = tf.InteractiveSession()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


*****
왜 InteractiveSession이 닫히지 않는것일까요ㅜㅜㅜ
eval()은 세션이 진행중일때만 실행 가능하다고 합니다ㅜㅜㅜ


In [106]:
pprint.pprint(t.eval())
print('shape는 겉껍질부터 1뭉텅이->2뭉텅이->3뭉텅이->4뭉텅이',tf.shape(t).eval())
print('rank는 괄호 갯수', tf.rank(t).eval())

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]], dtype=int32)
shape는 겉껍질부터 1뭉텅이->2뭉텅이->3뭉텅이->4뭉텅이 [1 2 3 4]
rank는 괄호 갯수 4


####Axis

In [131]:
print('rank가 {0} 개 -> axis {0}개'.format(tf.rank(t).eval()))
z = np.array(range(0, tf.rank(t).eval()) )
z = z[::-1]
print('안쪽에서 부터 axis {0}'.format(np.array(z)),'\n')
#print('밖쪽에서 부터 axis {0}'.format(np.array(range(0,tf.rank(t).eval()))))

a =\
[ #axis = 0, -4
    [ #axis = 1, -3
        [ #axis = 2, -2
            [1,2,3,4], #axis = 3, -1
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]
 
  #shape도 밖부터, axis도 밖부터 센다

rank가 4 개 -> axis 4개
안쪽에서 부터 axis [3 2 1 0] 



In [133]:
#reduce_mean 평균, 의미 줄이기
#reduce_sum 지정한 axis의 원소들을 '하나의 원소'로 합친다고 생각하자 마치 2048게임처럼!

x = [[1., 2.],
    [3., 4.]]
tf.reduce_sum(x).eval() #x를 하나로 만들어라

10.0

In [137]:
tf.reduce_sum(x, axis=0).eval() #axis0을 하나로 만들어라

'''
x = [[1., 2.],
    [3., 4.]]
x' = reduce_sum(x, axis=0).eval()
x' = [[1], [2]]<-axis=0의 괄호, axis=0에는 2개의 원소가 있었다
이 원소를 하나로 통합해버리고[1]+[2]  axis =0만 남긴다
x' = [[1]+[2]]
'''

x_ = tf.reduce_sum(x, axis=0).eval()
print(x_)

[4. 6.]


In [138]:
'''
x = [[1., 2.],
    [3., 4.]]
x' = reduce_sum(x, axis=1).eval()
x' = [[1.0, 2.0], [3.0, 4.0]<-axis=1의 괄호, axis=0에는 2개의 원소가 있었다]
이 원소를 하나로 통합해버리고 axis=1괄호안 에는 하나의 원소만을 남긴다
x' = [[1.0 + 2.0], [3.0 + 4.0]]
'''

x_ = tf.reduce_sum(x, axis=1).eval()
print(x_)

[3. 7.]


In [139]:
#argmax
#reshape
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])

t.shape

(2, 2, 3)

In [144]:
tf.reshape(t, shape=[-1, 3]).eval()

#t를 dim = 2가 되도록 reshape해라 그 대신 가장 안쪽의 원소갯수는 3개 나머지는 알아서 해

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [145]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

#t를 dim = 3가 되도록 reshape해라 가장 안쪽의 원소갯수는 3개, 그다음에는 1개 나머지는 알아서 해

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [149]:
tf.reshape(t, shape=[-1, -1, 3]).eval()

InvalidArgumentError: ignored

알아서 해! 라는 뜻의 -1은 한번만 쓰고, 지정해주는 갯수(위에서 보면 1이나 3)는 나누어 떨어지게 줘야한다

In [161]:
#squeeze와 expand
print(tf.squeeze([[0], [1], [2]]).eval(),'\n')
print(tf.expand_dims([0, 1, 2], 1).eval(),'\n')

[0 1 2] 

[[0]
 [1]
 [2]] 



In [162]:
print(tf.expand_dims([[0, 1, 2],[3, 4, 5]], 1).eval(),'\n')
print(tf.expand_dims([[0, 1, 2],[3, 4, 5]], 0).eval(),'\n')

[[[0 1 2]]

 [[3 4 5]]] 

[[[0 1 2]
  [3 4 5]]] 



강의에서 expand_dims을 설명하실때 얼마를 expand할꺼냐 라고 하셨는데

expand_dims은 1차원만을 키울 수 있다고 합니다.

(Inserts a dimension of 1 into a tensor's shape)

tf.expand_dims(

    input,
    
    axis=None,
    
    name=None,
    
    dim=None
    
)

인자가 위와 같으니 1은 axis를 말하는것 아닐까요?
바로 위 sell실행을 보면 맞는것 같아요

In [167]:
print(tf.squeeze([[[0], [1], [2]],[[3], [4], [5]]]).eval(),'\n')
#print(tf.squeeze([[[0], [1], [2]],[[3], [4], [5]]], 1).eval(),'\n')

[[0 1 2]
 [3 4 5]] 



In [190]:
y = [[[[[[[0]]],[[[1]]],[[[2]]]]], [[[[[0]]],[[[1]]],[[[2]]]]]]]
print(tf.shape(np.array(y)).eval(),'\n')

y = tf.squeeze(y)
print(tf.shape(y).eval(),'\n')
#squeeze는 size가 1인 차원들을 지워버린다

[1 2 1 3 1 1 1] 

[2 3] 



In [191]:
#one_hot
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [192]:
tf.one_hot([[0], [1], [2], [0]], depth=5).eval()

array([[[1., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0.]],

       [[0., 0., 1., 0., 0.]],

       [[1., 0., 0., 0., 0.]]], dtype=float32)

one hot은 rank를 증가시킴

3->one hot, depth = 3->[0, 0, 1]

[3]->one hot, depth =3->[[0,0,1]]

In [197]:
tf.reshape(tf.one_hot([[0], [1], [2], [0]], depth=5), shape=[-1, 5]).eval()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.]], dtype=float32)

In [203]:
#casting 어떠한 값을 원하는 형태의 자료형으로 cast한다
#stack쌓기
#ones_like(a) a와 형태가 같은 자료형을 만듬(원소는 모두 1)
#zeros_like(a) a와 형태가 같은 자료형을 만듬(원소는 모두 0)
#zip
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print('x is :', x,'y is: ', y)
    
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

x is : 1 y is:  4
x is : 2 y is:  5
x is : 3 y is:  6
1 4 7
2 5 8
3 6 9


In [202]:
for x, y in zip([[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]):
    print('x is :', x,'y is: ', y)

x is : [1, 2, 3] y is:  [7, 8, 9]
x is : [4, 5, 6] y is:  [10, 11, 12]
